### ISSUE TITLE
[Feature]: Add a new service for unregister_table

### ISSUE THREAD

**Issue by zeyaddeeb** [featureform/featureform#510]
Can I unregister tables or deleted entities?

**Comment by sdreyer** [comment]
Currently we do not support the ability to unregister tables or entities. 

One of the core features of Featureform is that lineage for features and training sets remains intact. This means that any resources (tables, transformations, etc)  cannot be deleted so that they are guaranteed to be available for any features, labels, or transformations that are dependent on them. 

We provide the ability to create variations of resources to allow modifications to them to be used, while keeping any previous variations available. 

However, we do have plans on the roadmap to both make updates to variations more seamless by updating all dependent resources automatically, and also selective deletions, where resources can be deleted if no other resources are dependent on them.
